name: Check changesets
on: [pull_request]

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          # without this changesets can't see `main` branch on PRs https://github.com/changesets/changesets/issues/517
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Use yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            '**/node_modules'
            '.yarn/cache'
            '.yarn/install-state.gz'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check changesets
        run: yarn changeset status --since origin/main
